
services:
  fastapi:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: toxicity_fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  monitoring:
    build:
      context: .
      dockerfile: monitoring/Dockerfile
    container_name: toxicity_monitoring
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: toxicity_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: toxicity
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
